language: node_js

node_js:
  - 15.8.0

cache:
  directories:
  - "node_modules"

notifications:
  email:
    on_success: never

branches:
  only:
    - main

install:
  - yarn

script:
  - yarn run build
